[package]
name = "evo-life"
description = "Organismes et écosystèmes : métabolismes, phénotype, populations microbiennes."
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
libm.workspace = true
evo-core.workspace = true
evo-planet.workspace = true
evo-genetics.workspace = true
rand.workspace = true
rand_distr.workspace = true
rayon.workspace = true

[dev-dependencies]
bincode.workspace = true
